- name: Assemble files
  assemble:
    attributes: "{{ item.attributes | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    decrypt: "{{ item.decrypt | default(omit) }}"
    delimiter: "{{ item.delimiter | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    ignore_hidden: "{{ item.ignore_hidden | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    regexp: "{{ item.regexp | default(omit) }}"
    remote_src: "{{ item.remote_src | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
    validate: "{{ item.validate | default(omit) }}"
  loop: "{{ structure_assembles }}"
  when: item.when | default(true)
