- hosts: all
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      structure_files:
        - path: /opt/dir
          state: directory
      # @TODO use the rest of tasks
